# Generated by Django 5.1 on 2024-08-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust_pilot_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
