# Generated by Django 5.1 on 2024-08-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust_pilot_backend', '0002_rename_review_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviewer_name',
            new_name='user',
        ),
    ]
