# Generated by Django 5.1 on 2024-08-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_pilot_backend', '0003_rename_reviewer_name_reviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='freelancer',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
