# Generated by Django 5.1 on 2024-08-13 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_pilot_backend', '0005_freelancer_users_alter_reviews_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trust_pilot_backend.freelancer'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trust_pilot_backend.users'),
        ),
    ]
