# Generated by Django 5.1 on 2024-08-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_pilot_backend', '0006_alter_reviews_freelancer_alter_reviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='freelancer_name',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
