# Generated by Django 5.1 on 2024-08-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust_pilot_backend', '0007_alter_freelancer_freelancer_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelancer',
            new_name='Freelancers',
        ),
    ]
