# Generated by Django 5.1 on 2024-08-14 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_pilot_backend', '0009_alter_freelancers_freelancer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trust_pilot_backend.freelancers'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trust_pilot_backend.users'),
        ),
    ]
